name: Checks

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8'] # add more versions here
        os: [ubuntu-latest] # add more platforms here (e.g. macos-latest, windows-latest)

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install codecov coverage pytest
        # install dependencies
        pip install -e .[all]
        # show installed packages
        pip freeze
    - name: Test with pytest
      run: |
        coverage run --source=sample-project setup.py test
    - name: Submit code coverage
      run: |
        coverage report -m
        codecov
